repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json

-   repo: https://github.com/microsoft/psscriptanalyzer
    rev: 1.22.1
    hooks:
    -   id: psscriptanalyzer
        name: PSScriptAnalyzer
        description: 'Static analysis for PowerShell scripts.'
        entry: pwsh -NoProfile -Command
        args: ['Invoke-ScriptAnalyzer', '-EnableExit']
        files: '\.(ps1|psm1|psd1)$'
        language: powershell
